# application.yml - Configuraci√≥n base

spring:
  application:
    name: sentiment-tech-api

  profiles:
    active: dev

    # postgresql
  datasource:
    url: jdbc:postgresql://${DB_PATH:localhost:5432/sentiment_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASS:123456}

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# API configuration
api:
  version: ${API_VERSION:v1}
  base-path: /api/${api.version}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${api.base-path}

# model-api
model:
  api:
    url: ${MODEL_API_URL:http://localhost:8000}